name: openstackclients
version: pike
summary: OpenStack Client tools
description: |
  OpenStackClient (aka OSC) is a command-line client for OpenStack
  that brings the command set for Compute, Identity, Image, Object
  Store and Block Storage APIs together in a single shell with a
  uniform command structure.
  .
  The primary goal is to provide a unified shell command structure
  and a common language to describe operations in OpenStack.
  .
  This snap provides the openstack command-line client and other
  project specific command-line clients.
confinement: classic
grade: devel

apps:
  openstack:
    command: bin/openstack
  glance:
    command: bin/glance
  neutron:
    command: bin/neutron
  nova:
    command: bin/nova
  cinder:
    command: bin/cinder
  aodh:
     command: bin/aodh
  barbican:
     command: bin/barbican
  ceilometer:
     command: bin/ceilometer
  cloudkitty:
     command: bin/cloudkitty
  designate:
     command: bin/designate
  freezer:
     command: bin/freezer
  glance:
     command: bin/glance
  heat:
     command: bin/heat
  ironic:
     command: bin/ironic
  magnum:
     command: bin/magnum
  manila:
     command: bin/manila
  mistral:
     command: bin/mistral
  monasca:
     command: bin/monasca
  murano:
     command: bin/murano
  senlin:
     command: bin/senlin
  swift:
     command: bin/swift
  tacker:
     command: bin/tacker
  trove:
     command: bin/trove
  vitrage:
     command: bin/vitrage
  watcher:
     command: bin/watcher

parts:
  openstackclients:
    plugin: python
    python-version: python3
    python-packages:
      - aodhclient
      - python-barbicanclient
      - python-ceilometerclient
      - python-cloudkittyclient
      - python-congressclient
      - python-designateclient
      - python-freezerclient
      - python-glanceclient
      - python-heatclient
      - python-ironicclient
      - python-keystoneclient
      - python-magnumclient
      - python-manilaclient
      - python-mistralclient
      - python-monascaclient
      - python-muranoclient
      - python-saharaclient
      - python-searchlightclient
      - python-senlinclient
      - python-swiftclient
      - python-tackerclient
      - python-troveclient
      - python-vitrageclient
      - python-watcherclient
      - python-zaqarclient
      - python-neutronclient
      - python-openstackclient
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/pike/upper-constraints.txt
    build-packages:
      - libffi-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - pkg-config
      - gcc
